---
# This playbook deploys a basic Splunk Universal Forwarder installation

- name: Apply prereqs to all nodes
  hosts: all
  gather_facts: no
  roles:
    - prereqs

- name: Install Splunk Universal Forwarder
  hosts: all
  roles:
    - uf-install
